# 审计日志配置
log_file: "security_audit.log"
max_size_mb: 10
backup_count: 5
alert_rules:
  - pattern: ".*(password|secret_key|token).*"
    level: "high"
    action: "alert"
  - pattern: "permission_denied"
    level: "medium"
    action: "notify"