# 权限管理配置
role_config:
  admin:
    - "create_user"
    - "delete_user"
    - "update_permission"
  manager:
    - "create_content"
    - "edit_content"
  user:
    - "view_content"
    - "edit_own_profile"

cache_ttl: 3600  # 缓存有效期(秒)
auto_refresh: 600  # 自动刷新间隔(秒)